[package]
name = "nrf52840-dk"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
categories = [ "hardware-support", "embedded", "no-std", ]
description = "IEEE 802.15.4 experiments with nRF52840 radio"
keywords = [ "arm", "cortex-m", "nrf52840", ]
license = "MIT"
readme = "README.md"
edition = "2018"

[dev-dependencies]
nrf52840-pac = "0.8"
nrf52840-hal = "0.8"
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-semihosting = "0.5"
cortex-m-semihosting = "0.3"
cortex-m-rtfm = "0.4"
ieee802154 = "0.3"
esercom = { path = "../esercom" }
nrf52-radio-802154 = { path = "../nrf52-radio-802154" }

