[package]
name = "nrf52840-dk"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
categories = [ "hardware-support", "embedded", "no-std", ]
description = "IEEE 802.15.4 experiments with nRF52840 radio"
keywords = [ "arm", "cortex-m", "nrf52840", ]
license = "MIT"
readme = "README.md"
edition = "2018"

[dev-dependencies]
nrf52840-pac = "0.8"
nrf52840-hal = "0.8"
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-itm = "0.4"
cortex-m-rtfm = "0.4"
ieee802154 = { git = "https://github.com/braun-embedded/rust-ieee802.15.4.git", branch = "master" }
esercom = { git = "https://blueluna@bitbucket.org/blueluna/esercom.git", branch = "master" }
nrf52-radio-802154 = { path = "../nrf52-radio-802154" }
nrf52-cryptocell = { path = "../nrf52-cryptocell" }
psila-crypto = { git = "https://blueluna@bitbucket.org/blueluna/psila.git" }
psila-data = { git = "https://blueluna@bitbucket.org/blueluna/psila.git", features = ["core"] }
bbqueue = { git = "https://github.com/jamesmunns/bbqueue" }
psila-service = { git = "https://blueluna@bitbucket.org/blueluna/psila.git", features = ["core"] }
