[package]
name = "nrf52840-mdk"
version = "0.0.1"
authors = ["Erik Svensson <erik.public@gmail.com>"]
edition = "2018"

[dev-dependencies]
nrf52840-pac = "0.8"
nrf52840-hal = "0.8"
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-semihosting = "0.5"
cortex-m-semihosting = "0.3"
cortex-m-rtfm = "0.4"
ieee802154 = "0.3"
esercom = { git = "https://blueluna@bitbucket.org/blueluna/esercom.git", branch = "master" }
nrf52-radio-802154 = { path = "../nrf52-radio-802154" }
bbqueue = { git = "https://github.com/jamesmunns/bbqueue" }
nrf52-cryptocell = { path = "../nrf52-cryptocell" }
psila-crypto-trait = { git = "https://blueluna@bitbucket.org/blueluna/psila.git" }